### ISSUE TITLE
contact button hidden

### ISSUE THREAD

**Issue by IlayTissona** [hubermanophir/pre-course-2021-final-boilerplate#1]
contact buttons are too low, one of them is hidden and only little part of it is showing

**Comment by listguy** [comment]
@IlayTissona  Be more specific.
what are your screen resolutions? 
'too low' relative to what? 
which one is hidden? 
is it hidden all the time? 
etc...

**Comment by IlayTissona** [comment]
@listguy 
happened in any screen resolution
too low in general, it's position is fixed too low
don't know which one, because it is hidden
and yes, it is hidden all the time

**Comment by hubermanophir** [comment]
thank you for the feedback I fixed the issue
